# Used with `roobre/reposettings`
#
# ```
# $ curl \
#     https://raw.githubusercontent.com/roobre/reposettings/master/reposettings.py \
#     -o reposettings.py && \
#   GITHUB_TOKEN=your-gh-token python reposettings.py ./settings.yaml
# ```

shared-config: &shared-config
  branch-protection:
    dismiss-stale-reviews: false
    required-review-count: 1
  protect-default-branch: true
  features:
    issues: true
    projects: false
    wiki: false
    downloads: true
  allow:
    squash-merge: true
    merge-commit: false
    rebase-merge: false
  delete-branch-on-merge: true

shared-labels: &shared-labels
  "good first issue":
    color: "00ff00"
  "Priority: Critical":
    color: "ff0000"
  "Priority: High":
    color: "ffa500"
  "Priority: Medium":
    color: "00ff00"
  "Priority: Low":
    color: "00ff00"
    replaces: "Priority: low"
  "Status: Blocked":
    color: "d93f0b"
  "Status: Cannot Reproduce":
    color: "3f3887"
  "Status: Confirmed":
    color: "bfd4f2"
  "Status: Draft":
    color: "81b056"
  "Status: Duplicate":
    color: "cfd3d7"
  "Status: Help Wanted":
    color: "008672"
  "Status: Testing Needed":
    color: "76ea93"
  "Status: Triage":
    color: "d15141"
  "Status: Won't Fix":
    color: "ffffff"
    replaces: "Status: Won't fix"
  "Type: Bug":
    color: "d73a4a"
  "Type: Cleanup":
    color: "3d8262"
  "Type: Documentation":
    color: "0075ca"
  "Type: Enhancement":
    color: "a2eeef"
  "Type: Invalid":
    color: "e4e669"
  "Type: Question":
    color: "d876e3"
  "Type: Idea Bank":
    color: "22b1a3"
  "Type: Refactor":
    color: "7a7014"
  "Type: Research":
    color: "fbca04"

alertmanager-config: &alertmanager-config
    <<: *shared-config
    labels+:
      "Area: Routes":
        color: "C5E1E3"
      "Area: Templates":
        color: "5319e7"
      "Area: Rules":
        color: "ff88aa"

grafana-agent-config: &grafana-agent-config
    <<:  *shared-config
    labels+:
      "Area: Metrics":
        color: "C5E1E3"
      "Area: Logs":
        color: "5319e7"
      "Area: Visualization":
        color: "ff88aa"

grafana-config: &grafana-config
    <<:  *shared-config
    labels+:
      "Area: Dashboard":
        color: "C5E1E3"
      "Area: Data Source":
        color: "5319e7"

loki-config: &loki-config
    <<:  *shared-config
    labels+:
      "Area: Push API":
        color: "C5E1E3"
      "Area: Log Proxy":
        color: "5319e7"
      "Area: Syslog":
        color: "ff88aa"

prometheus-config: &prometheus-config
    <<:  *shared-config
    labels+:
      "Area: prometheus_remote_write":
        color: "C5E1E3"
      "Area: prometheus_scrape":
        color: "5319e7"

repos:
  # rocks
  canonical/alertmanager-rock: *shared-config
  canonical/s3proxy-rock: *shared-config
  canonical/mimir-rock: *shared-config
  
  # bundles
  canonical/cos-lite-bundle: *shared-config
  
  # charms
  canonical/alertmanager-k8s-operator: *alertmanager-config
  canonical/avalanche-k8s-operator: *shared-config
  canonical/catalogue-k8s-operator: *shared-config
  canonical/cos-configuration-k8s-operator: *shared-config
  canonical/cos-proxy-operator: *shared-config
  canonical/grafana-k8s-operator: *grafana-config
  canonical/grafana-agent-k8s-operator: *grafana-agent-config
  canonical/karma-alertmanager-proxy-k8s-operator: *shared-config
  canonical/karma-k8s-operator: *shared-config
  canonical/loki-k8s-operator: *loki-config
  canonical/prometheus-k8s-operator: *prometheus-config
  canonical/prometheus-scrape-config-k8s-operator: *shared-config
  canonical/prometheus-scrape-target-k8s-operator: *shared-config
  canonical/traefik-k8s-operator: *shared-config  
  canonical/traefik-route-k8s-operator: *shared-config  
  
  # misc
  canonical/cos-tool: *shared-config  
  canonical/charming-actions: *shared-config  
  canonical/nrpe_exporter: *shared-config
  canonical/observability: *shared-config
  canonical/observability-libs: *shared-config
  
  # archived
  canonical/cassandra-k8s-operator: *shared-config
  canonical/elasticsearch-k8s-operator: *shared-config
  canonical/graylog-k8s-operator: *shared-config
  canonical/promql-transform: *shared-config
