name: Integration Tests

on:
  workflow_call: {}

jobs:
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 2.9/candidate
          provider: microk8s
          bootstrap-options: "--agent-version 2.9.37"
      - name: Patch hostpath-provisioner
        run: >
          sg microk8s -c "kubectl patch deployment hostpath-provisioner -n kube-system -p '{\"spec\": {\"template\": {\"spec\": {\"containers\": [{\"name\":\"hostpath-provisioner\", \"image\": \"cdkbot/hostpath-provisioner:1.3.0\" }] }}}}'"
      - name: Run integration tests
        run: tox -vve integration
